### PR TITLE
Added class for the multimeter voltcraft VC870 protocol which differs from the Fortune protocol.

### PR DESCRIPTION
**Pull request by M-Bab**
The interface used here are the most recent USB cables that appear as USB HID
device. They need a control ep configuration and read from interrupt endpoint
to receive the UART data arriving at the IC.

### CODE REVIEW

**Comment by ndejong** [comment]
Awesome!

I've just skimmed through and some initial comments.

The response data structure returned is considerably different to the Default, and while each instrument has different capabilities it would be helpful for downstream projects to get data-structures that have a similar arrangement, particularly for the `reading` data.

- keep the `aux value` and `aux unit` names consistent by using an underscore
- the `aux_value` and `aux_unit` should always be present, set them to `None` if they are not set, also for my understanding do the "aux" mode values relate to op_modes 90, 91 and 92 ?
- the term `operation_mode` relates to a hardware mode of operation, however the arrangement of the data returned by `_parse_packet_operation_mode()` seems to co-mingle mode, units and scale all into one, it looks like these could be separated and aligned with the same data structure as the Default

**Comment by M-Bab** [comment]
Thanks for the quick reply @ndejong !

I implemented your first 2 suggestions. Concerning the 3. I added some comments to make it more understandable. dict: key -> tuple was definitely the most compact way to achieve the decoding here. It is actually that the protocol mingles the 3 properties (mode, unit, scale) here and not me. I wanted to orientate my parse functions by the positions in the packet which they analyze. `_parse_packet_operation_mode` is about the first two bytes:

grafik

These two bytes define the measurement mode, the unit which is measured and also the base scaling factor to convert to SI units. I cannot see a practical advantage in splitting them - I would only need to make the decision tree or dict multiple times. I may change the value tuples in something different like dictionary or named tuple, if you think that helps.

**Comment by ndejong** [comment]
Hi @M-Bab - I really must apologize for not catching this sooner - was another Pull request that came in that caused me to (re)discover this one - working on this now

**Comment by ndejong** [comment]
Packaged and released in pip package 0.4.0 -
* https://pypi.org/project/digital-multimeter/

Thanks for your submission and extended patience in getting to this one

**Comment by M-Bab** [comment]
Thanks a lot @ndejong . I was in no hurry for this feature otherwise I would have reminded of the PR. Still happy that it made its way into the module.

**Comment by M-Bab** [comment]
Thanks for completing this. I am used to that PRs on github might need some time :smile:

**Pull request merged**
